### ISSUE TITLE
"new-cap" rule errors on code from external libs

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/eslint-config-sparkpost#2]
If you use a library that uses a capital letter method, eslint will error out.

```
let unzip = require('unzip');

unzip.Parse();
```

```
error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap
```

In my opinion the advantage of this rule isn't really worth the bother if that's how it works, I'd prefer to just turn it off. Thoughts?

**Comment by beardyman** [comment]
I think its good for our own code though.  I think it's pretty rare to find a lib with capitalized methods.  I would rather disable it in those cases.
